server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/driver_db?currentSchema=driver
    username: postgres
    password: ${DB_PASSWORD:admin} # pragma: allowlist-secret
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: driver
        format_sql: true
