server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iam_db?currentSchema=iam
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: iam
        format_sql: true
