server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db?currentSchema=billing
    username: postgres
    password: ${DB_PASSWORD:admin} # pragma: allowlist-secret
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: billing
        format_sql: true
