server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pricing_db?currentSchema=pricing
    username: postgres
    password: ${DB_PASSWORD:admin} # pragma: allowlist-secret
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: pricing
        format_sql: true
