server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trip_db?currentSchema=trip
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: trip
        format_sql: true
